source:
  type: folder                # folder|video|rtsp|gige
  uri: "assets"              # 默认读取仓库内示例图片（assets/test.jpg）

engine:
  type: rknn                 # onnx|rknn（RK3588 上使用 rknn）
  model: "models/best.rknn"  # 板子部署路径: $DEST/models/
  imgsz: 640

nms:
  conf_thres: 0.50
  iou_thres: 0.50
  topk: 300

perf:
  warmup: 5
  async: false

output:
  type: tcp
  ip: "127.0.0.1"
  port: 9000

classes: "config/person_classes.txt"
